[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = "0.27"
uefi-services = "0.24"

[[bin]]
name = "os"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

[profile.dev]
panic = "abort"