[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.35", features = ["panic_handler", "alloc"] }
x86_64 = "0.15"
uart_16550 = "0.4"
spin = "0.10"
pic8259 = "0.11"
linked_list_allocator = "0.10"
aes-gcm = { version = "0.10", default-features = false, features = ["aes"] }
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
generic-array = "0.14"

[[bin]]
name = "os"
path = "src/main.rs"

[features]
default = ["alloc"]
uefi = ["alloc"]
alloc = []

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

[profile.dev]
panic = "abort"